"""init

Revision ID: 582c3c0843f8
Revises: 6ffa73d90b7c
Create Date: 2025-05-18 18:28:20.688839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '582c3c0843f8'
down_revision = '6ffa73d90b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
