"""init

Revision ID: 6e7d63129cdb
Revises: 32a83fd20e26
Create Date: 2025-05-20 15:44:31.929201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e7d63129cdb'
down_revision = '32a83fd20e26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
