"""init

Revision ID: 32a83fd20e26
Revises: 582c3c0843f8
Create Date: 2025-05-20 15:28:26.849351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32a83fd20e26'
down_revision = '582c3c0843f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('user_id', sa.String(), nullable=False))
    op.create_foreign_key(op.f('fk_projects_user_id_users'), 'projects', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_projects_user_id_users'), 'projects', type_='foreignkey')
    op.drop_column('projects', 'user_id')
    # ### end Alembic commands ###
